server.port: 8089
config:
  persistenceType: "RdfFiles"
  rdfFolder: D:\Dev\sddms\rdf\
  ontologyFile: D:\Dev\sddms\ontology.owl
  ontologyFormat: "N3"
  rdfFormat: "NTRIPLES"
  managedUri: "http://www.example.com/"
  importExternalWebResources: false
  resourcesPerFile: 1000